### ISSUE TITLE
[Feature Request] "slidesToShow" slide the amount of slidesToShow > 1

### ISSUE THREAD

**Issue by webfacer** [lukaszflorczak/vue-agile#111]
Hi,

could we get a feature where we slide the same amount of slidesToShow is bigger than 1. So what i mean is when: Say we have 10 images
`array(1,2,3,4,5,6,7,8,9,10)`
For the example we showing now the first 5 indexes. At the "next" - click we show the 5th index.
Example on first show: `array(1,2,3,4,5)` after clicking next i would see the rest and the 5indexes before are gone in the background:  the next five images of the main array above `array(6,7,8,9,10)`
I hope i could explain it to you as good as i can, because my english isn´t that well :)

**Comment by dzonivojvodic** [comment]
@webfacer Use slidesToScroll="numberOfSlides"
`<Carousel
              :slides-to-show="2"
              :slides-to-scroll="2"
              :dots="true">
                <div>Slide 1</div>
                <div>Slide 2</div>
                <div>Slide 3</div>
                <div>Slide 4</div>
 </Carousel>`

**Comment by tisha077** [comment]
@dzonivojvodic 
when I use your option, I observe a bug after passing the second "circle" - an empty space and the slider "leaves" to the left

**Comment by dzonivojvodic** [comment]
> @dzonivojvodic
> when I use your option, I observe a bug after passing the second "circle" - an empty space and the slider "leaves" to the left

Try removing the dots if not needed or use the v-if option if slides are dynamically shown.

**Comment by webfacer** [comment]
thanks did the trick. sry could only now testing it. thanks @dzonivojvodic

**Comment by webfacer** [comment]
i know it is not the same issue, as described but follows with this issue. like @dzonivojvodic said it is an empty space when reaching the end of slide-items.
and removing the dots don´t solve the issue.

**Comment by lukaszflorczak** [comment]
@webfacer It should be fixed in v1.1

**Comment by webfacer** [comment]
i will try it thanks for the info

**Comment by webfacer** [comment]
i am using 1.1.3 and it still not working. it holds on the last after reaching the first element but when reashing last element it is not stoping

**Comment by lukaszflorczak** [comment]
Thanks, I'll check it one more time soon.

**Comment by webfacer** [comment]
Hi again,
if it helps this is how my template looks like:

```vue
          <div class="col-sm-5 calendarFilterSection calendarFilterDay">
            <div class="content">
              <pre>{{ dateList }}</pre>
              <agile
                v-if="dateList"
                ref="slider"
                :options="defaultCustomOptions"
              >
                <div
                  :class="[
                    'slide',
                    'slide--' + index,
                    { active: isActive(date.day) }
                  ]"
                  v-for="(date, index) in dateList"
                  :key="index"
                  @click.prevent="eventFilterItemsByDay(date.day, date.month)"
                >
                  <span>{{ date.day }}</span>
                  <span>{{ date.month }}</span>
                </div>
                <template slot="prevButton">prev</template>
                <template slot="nextButton">next</template>
              </agile>
            </div>
          </div>
```
This are the custom options which i use:
```vue
  private customOptions = {
    dots: false,
    speed: 500,
    infinite: false,
    initialSlide: 4,
    slidesToShow: 5,
    slidesToScroll: 3,

    responsive: []
  };
```
And this how i populate dateList: 
I am using momentjs to create a range 14 weeks left offset and 14 weeks right offset

an example from dataList it´s data:
```json
[
  {
    "object": "2020-06-05T00:00:00.000Z",
    "day": 5,
    "month": "Juni"
  },
  {
    "object": "2020-06-06T00:00:00.000Z",
    "day": 6,
    "month": "Juni"
  },
  {
    "object": "2020-06-07T00:00:00.000Z",
    "day": 7,
    "month": "Juni"
  },
  {
    "object": "2020-06-08T00:00:00.000Z",
    "day": 8,
    "month": "Juni"
  },
  {
    "object": "2020-06-09T00:00:00.000Z",
    "day": 9,
    "month": "Juni"
  },
  {
    "object": "2020-06-10T00:00:00.000Z",
    "day": 10,
    "month": "Juni"
  },
  {
    "object": "2020-06-11T00:00:00.000Z",
    "day": 11,
    "month": "Juni"
  },
  {
    "object": "2020-06-12T00:00:00.000Z",
    "day": 12,
    "month": "Juni"
  },
  {
    "object": "2020-06-13T00:00:00.000Z",
    "day": 13,
    "month": "Juni"
  },
  {
    "object": "2020-06-14T00:00:00.000Z",
    "day": 14,
    "month": "Juni"
  },
  {
    "object": "2020-06-15T00:00:00.000Z",
    "day": 15,
    "month": "Juni"
  },
  {
    "object": "2020-06-16T00:00:00.000Z",
    "day": 16,
    "month": "Juni"
  },
  {
    "object": "2020-06-17T00:00:00.000Z",
    "day": 17,
    "month": "Juni"
  },
  {
    "object": "2020-06-18T00:00:00.000Z",
    "day": 18,
    "month": "Juni"
  },
  {
    "object": "2020-06-19T00:00:00.000Z",
    "day": 19,
    "month": "Juni"
  },
  {
    "object": "2020-06-20T00:00:00.000Z",
    "day": 20,
    "month": "Juni"
  },
  {
    "object": "2020-06-21T00:00:00.000Z",
    "day": 21,
    "month": "Juni"
  },
  {
    "object": "2020-06-22T00:00:00.000Z",
    "day": 22,
    "month": "Juni"
  },
  {
    "object": "2020-06-23T00:00:00.000Z",
    "day": 23,
    "month": "Juni"
  },
  {
    "object": "2020-06-24T00:00:00.000Z",
    "day": 24,
    "month": "Juni"
  },
  {
    "object": "2020-06-25T00:00:00.000Z",
    "day": 25,
    "month": "Juni"
  },
  {
    "object": "2020-06-26T00:00:00.000Z",
    "day": 26,
    "month": "Juni"
  },
  {
    "object": "2020-06-27T00:00:00.000Z",
    "day": 27,
    "month": "Juni"
  },
  {
    "object": "2020-06-28T00:00:00.000Z",
    "day": 28,
    "month": "Juni"
  },
  {
    "object": "2020-06-29T00:00:00.000Z",
    "day": 29,
    "month": "Juni"
  },
  {
    "object": "2020-06-30T00:00:00.000Z",
    "day": 30,
    "month": "Juni"
  },
  {
    "object": "2020-07-01T00:00:00.000Z",
    "day": 1,
    "month": "Juli"
  },
  {
    "object": "2020-07-02T00:00:00.000Z",
    "day": 2,
    "month": "Juli"
  },
  {
    "object": "2020-07-03T00:00:00.000Z",
    "day": 3,
    "month": "Juli"
  }
]
```

**Comment by webfacer** [comment]
@notice: another found i did. if i using "infinite" `true`. it is working but i do not get it why it is not stopping on last item. And i would need it to stop beacuse the dates do not caluculate it self again at the end.
