### ISSUE TITLE
Chrome Intervention: Unable to preventDefault inside passive event listener due to target being treated as passive.

### ISSUE THREAD

**Issue by grandgeorg** [lukaszflorczak/vue-agile#141]
There is a error in google chrome browser:

```
[Intervention] Unable to preventDefault inside passive event listener
due to target being treated as passive.
```
This happens due to line 221 in Agile.vue 

https://github.com/lukaszflorczak/vue-agile/blob/18f8336215874b310d780675d70c8a30728bc80d/src/Agile.vue#L221

First of all using ```document.ontouchmove``` is quite bad practice, as it is not widely implemented as stated in the note in https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ontouchmove

The actual problem is, that the GlobalEventHandlers.ontouchmove is treated as passive and because of that, it cannot call ```preventDefault()```, as explained under options - passive in
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Parameters

"A Boolean which, if true, indicates that the function specified by listener will never call preventDefault(). If a passive listener does call preventDefault(), the user agent will do nothing other than generate a console warning. See Improving scrolling performance with passive listeners to learn more."

So instead you would have to call once:

```js
document.addEventListener("touchmove", somefunction, {passive: false})
```
Within the callback you could than decide to call ```preventDefault()``` on the event, if you want to disable default scrolling. For that you would have to set some variable in the state ...

**Comment by jbiancovns** [comment]
Same here

**Comment by lukaszflorczak** [comment]
Should be fixed in version `v1.0.12`

**Comment by bogdanfer** [comment]
Hi! Still getting this error, installed via npm today v1.1.3.

**Comment by lukaszflorczak** [comment]
@bogdanfer Hey. What version of browser and OS do you use?

**Comment by bogdanfer** [comment]
macOS Mojave 10.14.6 
chrome 80.0.3987.163

**Comment by lukaszflorczak** [comment]
@bogdanfer I investigated the topis once again. Could you change the version from branch with the fix?

```bash
yarn add https://github.com/lukaszflorczak/vue-agile.git/#issue-141-Chrome_Intervention_Unable_to_preventDefault_inside_passive_event_listener_due_to_target_being_treated_as_passive

**Comment by justindantzer** [comment]
@lukaszflorczak Just tested using the noted version, and still seeing the error, but much less frequently. With the noted version, I saw an error a handful of times with a bunch of swipes. With version 1.1.3 installed, errors trigger constantly while _dragging/touching_ to swipe.

**Comment by chrisdelbuck** [comment]
Also seeing this with vue-agile v1.1.3 in Chrome 81.0.4044.138 (macOS). 

methods.js line 17
`document.ontouchmove = (e) => e.preventDefault()`

**Comment by Jangle282** [comment]
Same problem with v1.1.3  with Chrome  83.0.4103.97 
Same method as chrisdelbuck mentions
document.ontouchmove = (e) => e.preventDefault()

Maybe this can help - after reading this https://stackoverflow.com/a/42288386
I added the following css property

```
.agile__list {
        touch-action: none
}
```

As a temporary fix - which stops the errors but I guess I'll find out what other problems that causes later on!

**Comment by kyusupov33** [comment]
same here...
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>

chrome 83.0.4103.97

**Comment by kyusupov33** [comment]
.agile__list {
  touch-action: none;
}

doesn't helped

**Comment by DRBragg** [comment]
Unfortunately I'm running into the same issue
