### ISSUE TITLE
mouse swipe

### ISSUE THREAD

**Issue by FranckFreiburger** [lukaszflorczak/vue-agile#43]
When I swipe to the next or previous slide with the mouse, vue-agile gets completely crazy when I move my mouse over the slides (maybe the mouseup has not been trapped).
(v0.3.3 from npm)

**Comment by lukaszflorczak** [comment]
I noticed this bug at the same time and I released `v0.3.4` a moment ago.

**Comment by FranckFreiburger** [comment]
An issue is still present with mouse swipe (v0.3.5): mouse swipe multiple times seems to start several timers.

**Comment by lukaszflorczak** [comment]
I checked in two of my projects where I use `v0.3.5`. What settings are you use for your carousel? I will try to use the same.

**Comment by FranckFreiburger** [comment]
```
<vue-agile
	class="vue-agile"
	:mobile-first="false"
	:arrows="false"
	:autoplay="true"
	:autoplay-speed="5000"
	:speed="1000"
>
```
Inner structure looks like this:
```
<div>
	<div class="titleWrapper">
		<h3>...</h3>
	</div>
	<div class="imgWrapper">
		<img src='...'>
	</div>
</div>
```
... repeated multiple times

(tested with google chrome 62, vue v2.5.2)

**Comment by lukaszflorczak** [comment]
OK, I see now. This happens with autoplay. I will fix it today.

**Comment by FranckFreiburger** [comment]
thanks !

**Comment by lukaszflorczak** [comment]
Hey, I think it's fixed. Could you check the latest update?

**Comment by FranckFreiburger** [comment]
fixed ! thanks !
